package services

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/chromedp/chromedp"
	"github.com/phpdave11/gofpdf"
)

type MixedReportResult struct {
	PNGPath string `json:"png_path"`
	PDFPath string `json:"pdf_path"`
}

type ReportPDFItem struct {
	Title   string
	Value   string
	Details string
}

type ReportPDFData struct {
	Title        string
	SubTitle     string
	GeneratedAt  string
	Summary      []ReportPDFItem
	Findings     []ReportPDFItem
	FooterRemark string
}

func GenerateMixedReportFiles() (*MixedReportResult, error) {
	outputDir := os.Getenv("REPORT_OUTPUT_DIR")
	if outputDir == "" {
		outputDir = "./tmp/reports"
	}

	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return nil, fmt.Errorf("create output dir failed: %w", err)
	}

	timestamp := time.Now().Format("2006-01-02_15-04-05")
	pngPath := filepath.Join(outputDir, fmt.Sprintf("capture-report-%s.png", timestamp))
	pdfPath := filepath.Join(outputDir, fmt.Sprintf("openvas-report-%s.pdf", timestamp))

	if err := captureFrontendPNG(pngPath); err != nil {
		return nil, err
	}

	if err := generateStaticPDF(pdfPath); err != nil {
		return nil, err
	}

	return &MixedReportResult{
		PNGPath: pngPath,
		PDFPath: pdfPath,
	}, nil
}

func captureFrontendPNG(filePath string) error {
	targetURL := os.Getenv("FRONTEND_CAPTURE_URL")
	if targetURL == "" {
		targetURL = "http://frontend/capture"
	}

	chromePath := os.Getenv("CHROME_PATH")

	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", true),
		chromedp.Flag("disable-gpu", true),
		chromedp.Flag("hide-scrollbars", true),
		chromedp.Flag("no-sandbox", true),
		chromedp.Flag("disable-dev-shm-usage", true),
		chromedp.WindowSize(1600, 900),
	)

	if chromePath != "" {
		opts = append(opts, chromedp.ExecPath(chromePath))
	}

	allocCtx, cancel := chromedp.NewExecAllocator(context.Background(), opts...)
	defer cancel()

	ctx, cancel := chromedp.NewContext(allocCtx)
	defer cancel()

	ctx, cancel = context.WithTimeout(ctx, 360*time.Second)
	defer cancel()

	var pngBuf []byte

	err := chromedp.Run(ctx,
		chromedp.Navigate(targetURL),
		chromedp.WaitVisible(`#capture-root`, chromedp.ByID),
		chromedp.Sleep(2*time.Second),
		chromedp.FullScreenshot(&pngBuf, 95),
	)
	if err != nil {
		return fmt.Errorf("capture screenshot failed (url=%s): %w", targetURL, err)
	}

	if err := os.WriteFile(filePath, pngBuf, 0644); err != nil {
		return fmt.Errorf("write png file failed: %w", err)
	}

	return nil
}

func generateStaticPDF(filePath string) error {
	data := ReportPDFData{
		Title:       "OpenVAS Security Report",
		SubTitle:    "Automated vulnerability summary report",
		GeneratedAt: time.Now().Format("2006-01-02 15:04:05"),
		Summary: []ReportPDFItem{
			{Title: "Project", Value: "OpenVAS Dashboard"},
			{Title: "Environment", Value: "Production"},
			{Title: "Report Type", Value: "Backend Generated PDF"},
			{Title: "Generated By", Value: "Go Service"},
		},
		Findings: []ReportPDFItem{
			{
				Title:   "Critical Findings",
				Value:   "2",
				Details: "พบช่องโหว่ระดับวิกฤต 2 รายการ ควรเร่งดำเนินการแก้ไขทันที",
			},
			{
				Title:   "High Findings",
				Value:   "5",
				Details: "พบช่องโหว่ระดับสูง 5 รายการ ควรวางแผนแก้ไขโดยเร็ว",
			},
			{
				Title:   "Medium Findings",
				Value:   "9",
				Details: "พบช่องโหว่ระดับกลาง 9 รายการ ควรติดตามในรอบถัดไป",
			},
			{
				Title:   "Low Findings",
				Value:   "12",
				Details: "พบช่องโหว่ระดับต่ำ 12 รายการ ใช้สำหรับติดตามและปรับปรุงต่อเนื่อง",
			},
		},
		FooterRemark: "This PDF is generated directly by backend Go code and sent as a public link via LINE.",
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetTitle(data.Title, false)
	pdf.SetAuthor("OpenVAS Backend", false)
	pdf.SetCreator("Go Backend Service", false)
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)
	pdf.AddPage()

	pdf.SetFont("Arial", "B", 20)
	pdf.CellFormat(0, 12, data.Title, "", 1, "L", false, 0, "")

	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(90, 90, 90)
	pdf.CellFormat(0, 8, data.SubTitle, "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 8, "Generated At: "+data.GeneratedAt, "", 1, "L", false, 0, "")
	pdf.Ln(4)

	pdf.SetTextColor(0, 0, 0)

	pdf.SetFont("Arial", "B", 14)
	pdf.CellFormat(0, 10, "1) Report Summary", "", 1, "L", false, 0, "")
	pdf.Ln(1)

	for _, item := range data.Summary {
		pdf.SetFont("Arial", "B", 11)
		pdf.CellFormat(45, 8, item.Title+":", "", 0, "L", false, 0, "")
		pdf.SetFont("Arial", "", 11)
		pdf.MultiCell(0, 8, item.Value, "", "L", false)
	}
	pdf.Ln(3)

	pdf.SetFont("Arial", "B", 14)
	pdf.CellFormat(0, 10, "2) Findings Overview", "", 1, "L", false, 0, "")
	pdf.Ln(1)

	for i, item := range data.Findings {
		pdf.SetFont("Arial", "B", 12)
		pdf.CellFormat(0, 8, fmt.Sprintf("%d. %s", i+1, item.Title), "", 1, "L", false, 0, "")

		pdf.SetFont("Arial", "", 11)
		pdf.CellFormat(20, 8, "Count:", "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 8, item.Value, "", 1, "L", false, 0, "")

		pdf.CellFormat(20, 8, "Detail:", "", 0, "L", false, 0, "")
		pdf.MultiCell(0, 8, item.Details, "", "L", false)
		pdf.Ln(2)
	}

	pdf.Ln(4)
	pdf.SetFont("Arial", "I", 10)
	pdf.SetTextColor(100, 100, 100)
	pdf.MultiCell(0, 6, data.FooterRemark, "", "L", false)

	if err := pdf.OutputFileAndClose(filePath); err != nil {
		return fmt.Errorf("write pdf file failed: %w", err)
	}

	return nil
}